INSERT INTO TBL_CITY(NAME, ESTADO, POPUL, PIB) VALUES ('Itu', 'SP', '175.568', '84B');
INSERT INTO TBL_CITY(NAME, ESTADO, POPUL, PIB) VALUES ('Salto', 'SP', '119.736', '9.3B');
INSERT INTO TBL_CITY(NAME, ESTADO, POPUL, PIB) VALUES ('Cabreuva', 'SP', '50.429', '6B');